name: sequences
description: Game  math riddle to find the n number in sequences.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7+2
  navigatorium:
    path: /Users/lumos/personal/project/flutter-plugin/navigatorium
  in_app_update: ^1.1.11
  firebase_analytics: ^5.0.11
  flutter_mobx: ^1.1.0
  admob_flutter: ^1.0.0-beta.3
  toast: ^0.1.5
  loading_indicator: ^1.1.0
  audioplayers: ^0.15.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-light.png
    - assets/images/logo-dark.png
    - assets/images/sequence-icon-square.png
    - assets/images/gear.png
    - assets/images/close.png
    - assets/images/check.png
    - assets/images/light-on.png
    - assets/images/eraser.png
    - assets/images/check-circle.png
    - assets/images/lock.png
    - assets/images/coret-logo.png
    - assets/images/no-light.png
    - assets/images/thanks-for-playing.png

    - assets/stages/basic.json


    - assets/sounds/sequence-theme.mp3
    - assets/sounds/sequence-landing-page.mp3
    - assets/sounds/cobell.mp3
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
